name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env: 
          APP_URL: "http://localhost:3000"
          NEXT_PUBLIC_API_BASE_URL: "https://devstore-api-blue.vercel.app"
        with:
          build: npm run build
          start: npm start